---
title: "R Notebook"
output: html_notebook
---

```{r}
pillow <- read.csv(file = 'C:/Users/dimit/Downloads/data_for_research.csv')
pillow
```

```{r}

plotting <- function(cur_dat, bin, label){
  xrange = c(min(cur_dat),max(cur_dat))
  hist(cur_dat,
       probability = T, 
       breaks = bin, 
       xlim = xrange,
       main = label,
       col = "lightblue");
  lines(density(cur_dat),xlim=xrange, col = "blue")
  x <- seq(min(cur_dat),max(cur_dat), by=.01)
}

```

```{r}
plotting(pillow$sr, 20, "Snorring rate")
plotting(pillow$sh, 20, "Hours of sleep")
plotting(pillow$hr, 20, "Heart rate")

```

As we can see, all outcomes are equally possible.

```{r}
linear_model <- lm(pillow$sr ~ pillow$hr)
plot(pillow$sr, pillow$hr, pch=1, xlim=c(50,100), col = "blue")
abline(linear_model, col = "purple")
summary(linear_model)
```

Sleeping hours and stress level.\
We cut all data where sleeping hours were less then 1 hour of seeping, becouse we assume that this data is mistakenly taken.

```{r}
pillow$hight <- pillow$sh > 5.0
pillow
summary(pillow)
```

```{r}
# ggplot(pillow,aes(x=sh,fill=factor(high)))+sl(alpha=0.5)+
#  xlab(label = "Fixed Acidity Level")+
#  ggtitle("Distribution of Fixed Acidity Levels")+
#  theme_minimal()
```
